### ISSUE TITLE
Replace Timeline

### ISSUE THREAD

**Issue by abhinemani** [SacMOIE/RAILS#2]
May 4: Program launch; open call for grant applications
June 15: Application deadline
June 19-July 1: Review and selection process by MOIE, Departments & Tech Council
July 2: Recommendations presented to Budget and Audit Committee
July 15: Winners announced; granting process begins
Oct/Nov (exact date TBD): City-wide “Demo-Day” Event, showcasing RAILS outcomes

**Comment by sac-moie** [comment]
Fixed
